apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      resources:
        limits:
          cpu: "200m"
          memory: "32Mi"
        requests:
          cpu: "100m"
          memory: "16Mi"
      command: [ "/bin/sh", "-c", "env" ]
  restartPolicy: Never
