apiVersion: v1
kind: Pod
metadata:
  name: tester
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-cx", "echo $(SPECIAL_LEVEL_KEY) $(SPECIAL_TYPE_KEY)" ]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: SPECIAL_LEVEL
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: SPECIAL_TYPE
      resources:
        limits:
          cpu: "200m"
          memory: "32Mi"
        requests:
          cpu: "100m"
          memory: "16Mi"
  restartPolicy: Never
